.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "BATTLESHIP" "" "May 2021" "" ""
.SH "NAME"
\fBbattleship, nbbattleship\fR
.SH "CONTROLS"
RETURN/ENTER : Shoot
.TP
R : Rotate
.TP
hjkl/ARROW KEYS : Move cursor
.TP
q : Quit
.TP
F1 & F2 : Help on controls & gameplay
.TP
YOU CAN ALSO USE THE MOUSE!
.SH "GAMEPLAY"
Guess the location of your opponent\'s
.TP
ships and sink them! The player
.TP
who sinks all the opponent\'s ships wins\.
