.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "DARRT" "" "May 2021" "" ""
.SH "NAME"
\fBdarrt, nbdarrt\fR
.SH "GAMEPLAY"
If you hit a letter on keyboard, the letter on the
.P
screen will soon stop\. You have to aim for the
.P
center of the target using the moving letters\.
