.TH "LOGIK" "" "May 2021" "" ""
.SH "NAME"
\fBlogik\fR
.SH "CONTROLS"
rgypmRGY : put a specific color
.P
QQ : quit
.P
x : backspace
.SH "GAMEPLAY"
The computer generate random pattern of 5 colors
that you must guess\. You have 8 colors, and 10 lines
to guess with each 5 holes\. After you entered your 5
colors the computer will print you a hint, to help you:
.P
\'-\' : one of the colors doesn't match with the correct answere\.
.P
\'x\' : one of the colors is on the right place\.
.P
\'o\' : one of the colors match but is missplaced\.
.SH "HISTORY"
This is game is known as 
.B
Logik
in the eastern block (USSR), 
and 
.B 
Mastermind 
in the west block (USA)\.
