.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "MEMOBLOCKS" "" "May 2021" "" ""
.SH "NAME"
\fBmemoblocks, nbmemoblocks\fR
.SH "CONTROLS"
RETURN/ENTER : Reveal
.P
hjkl/ARROW KEYS : Move cursor
.P
q : Quit
.P
F1 & F2 : Help on controls & gameplay
.P
YOU CAN ALSO USE THE MOUSE!
.SH "GAMEPLAY"
Click on a tile to see the glyph it contains,
.P
then try to find a matching glyph the same way\.
.P
They form a pair only when you click a tile
.P
directly after the match\. The game ends when
.P
you have found all the matching pairs\.
