.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "RABBITHOLE" "" "May 2021" "" ""
.SH "NAME"
\fBrabbithole, nbrabbithole\fR
.SH "CONTROLS"
hjkl/ARROW KEYS : Move cursor
.P
q : Quit
.P
F1 & F2: Help on controls & gameplay (viewing these pages doesn\'t pause the timer!)
.P
PgDn,PgUp,\fI,\fR : Scroll
.SH "GAMEPLAY"
Try to gather all the carrots in the maze
.P
in the given time\. The determining factors
.P
are your choice of paths and the speed of
.P
your fingers\.
