.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "REVERSI" "" "May 2021" "" ""
.SH "NAME"
\fBreversi, nbreversi\fR
.SH "CONTROLS"
RETURN/ENTER : Put the piece
.P
hjkl/ARROW KEYS : Move cursor
.P
q : Quit
.P
F1 & F2 : Help on controls & gameplay
.P
YOU CAN ALSO USE THE MOUSE!
.SH "GAMEPLAY"
Players take turns placing disks on the board:
.P
1) Any pieces of the opponet\'s color that is bounded
.P
in a straight line between the piece just placed and
.P
another piece of the current player\'s color would turn
.P
to the current player\'s color\.
.P
2) You can only put pieces if at least one of your
.P
opponet\'s pieces turns into your color\.
.P
3) The game ends when neither side can do a move and
.P
the player with more pieces wins\.
