.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "SOS" "" "May 2021" "" ""
.SH "NAME"
\fBsos, nbsos\fR
.SH "CONTROLS"
hjkl/ARROW KEYS : Move cursor
.P
S & O : Write S or O
.P
q : Quit
.P
F1 & F2: Help on controls & gameplay
.P
PgDn,PgUp,\fI,\fR : Scroll
.P
YOU CAN ALSO USE THE MOUSE!
.SH "GAMEPLAY"
The game is similar to Tic Tac Toe:
.P
The players write S and O in the squares
.P
and making the straight connected sequence
.P
S\-O\-S makes you a score; obviously, the
.P
player with a higher score wins\.
