.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "SUDOKU" "" "May 2021" "" ""
.SH "NAME"
\fBsudoku, nbsudoku\fR
.SH "CONTROLS"
1 \- g : Enter number/character
.P
SPACE : Clear tile
.P
ARROW KEYS : Move cursor
.P
q : Quit
.P
n : New board
.P
r : Restart
.P
? : Hint (not like in other games)
.P
F1 & F2: Help on controls & gameplay
.P
PgDn,PgUp,\fI,\fR : Scroll
.P
YOU CAN ALSO USE THE MOUSE!
.SH "GAMEPLAY"
Fill the table with digits (and characters)
.P
so that all the rows, columns and smaller subregions
.P
contain all of the digits from 1 to 9 and all
.P
the alphabet letters from \'a\' to \'g\'\.
.SH "BUGS"
Doesn\'t guarantee a unique solution\. Attempts to fix that are welcome\.
