.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "CHECKERS" "" "May 2021" "" ""
.SH "NAME"
\fBcheckers, nbcheckers\fR
.SH "CONTROLS"
RETURN/ENTER : Select or move the piece
.P
hjkl/ARROW KEYS : Move cursor
.P
q : quit
.P
F1 & F2 : Help on controls & gameplay
.P
YOU CAN ALSO USE THE MOUSE!
.SH "GAMEPLAY"
1) The game starts with each player having 12 men;
.P
men can only diagonally move forwards
.P
(toward the opponet\'s side)\.
.P
2) Men can become kings by reaching the opponet\'s
.P
first rank; kings can diagonally move both forwards
.P
and backwards\.
.P
3) Pieces can capture opponet\'s pieces by jumping over them
.P
also they can capture several pieces at once by doing a
.P
chain of jumps\.
.P
4) You have to do a jump if you can\.
.P
5) A player wins when the opponet can\'t do a move e\. g\.
.P
all of their pieces are captured\.
