.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "FIFTEEN" "" "May 2021" "" ""
.SH "NAME"
\fBfifteen, nbfifteen\fR
.SH "CONTROLS"
RETURN/ENTER : Slide
.P
hjkl/ARROW KEYS : Move cursor
.P
q : Quit
.P
F1 & F2 : Help on controls & gameplay
.P
YOU CAN ALSO USE THE MOUSE!
.SH "GAMEPLAY"
Slide the tiles until the numbers and characters are
.P
in the right order\.
