.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "FISHER" "" "May 2021" "" ""
.SH "NAME"
\fBfisher, nbfisher\fR
.SH "CONTROLS"
UP & DOWN: Control the hook
.P
q: Quit
.P
This is a port of "Deep Sea Fisher", a MikeOS game\.
.SH "GAMEPLAY"
Catch a fish and reel it in for points
.P
The deeper the fish, the more points it is worth\.
.P
If a fish hits your line, you lose a hook\.
.P
When you run out of hooks, the game is over!
.P
This is a port of "Deep Sea Fisher", a MikeOS game\.
