.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "MINES" "" "May 2021" "" ""
.SH "NAME"
\fBmines, nbmines\fR
.SH "CONTROLS"
RETURN/ENTER : Examine for bombs
.P
SPACE : Flag/Unflag
.P
hjkl/ARROW KEYS : Move cursor
.P
q : Quit
.P
F1 & F2 : Help on controls & gameplay
.P
PgDn,PgUp,\fI,\fR : Scroll
.P
YOU CAN ALSO USE THE MOUSE!
.SH "GAMEPLAY"
Try to find the landmines in the field
.P
with logical reasoning: When you click
.P
on a tile ( a \'\.\' here), numbers may show
.P
up that indicate the number of landmines
.P
in adjacent tiles; you should find and
.P
avoid the landmines based on them; and
.P
clicking on a landmine would make you
.P
lose the game\.
