.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "PIPES" "" "May 2021" "" ""
.SH "NAME"
\fBpipes, nbpipes\fR
.SH "CONTROLS"
RETURN/ENTER : Place/Replace a pipe
.P
hjkl/ARROW KEYS : Move cursor
.P
p : Pause
.P
q : Quit
.P
f : Toggle fast flow
.P
F1 & F2 : Help on controls & gameplay
.P
YOU CAN ALSO USE THE MOUSE!
.SH "GAMEPLAY"
Keep maintaining the pipeline and
.P
don\'t let the sewage leak\.
